<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AocHelper\AocHelper.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="NLog" Version="6.0.6" />
      <PackageReference Include="NLog.Config" Version="4.7.15" />
      <PackageReference Include="NLog.Extensions.Logging" Version="6.1.0" />
    </ItemGroup>

    <ItemGroup>
      <None Update="nlog.config">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
